name: deploy

on:
  push:
    branches:
      - '*'
      # - disable
      # - main
      # - develop
      # - '*-autodoc'
      # - '!gh-pages'
    tags: ['*']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Set up UV
      uses: astral-sh/setup-uv@v7

    - name: Install python packages
      run: uv sync

    - name: Build
      working-directory: ${{ github.workspace }}
      run: |
        git tag
        tagname="${{ env.GITHUB_REF_SLUG }}"
        export tagname="${tagname%-autodoc}"
        echo $tagname
        for lang in ja en; do
          uv run sphinx-build -b html --color docs/${lang} docs/built/${lang}/html
        done

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs/built

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || github.ref_name == 'develop' || github.ref_type == 'tag'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: Download
      uses: actions/download-artifact@v5
      with:
        name: docs
        path: built-docs

    - name: Check downloaded docs
      run: |
        tree built-docs

    - name: Deploy Configuration
      run: |
          mkdir ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GHA_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

    - name: Push
      env:
        GIT_USER: "yomichi"
        GIT_EMAIL: "yomichi@tsg.jp"
      run: |
          is_tag=NO
          test "_$(echo ${GITHUB_REF:-'//'} | cut -d/ -f2)" = "_tags" && is_tag=YES
          cd ${GITHUB_WORKSPACE}
          tagname="${{ env.GITHUB_REF_SLUG }}"
          tagname=${tagname%-autodoc}
          echo $tagname
          rm -rf "gh-pages/man/${tagname}"
          mkdir -p "gh-pages/man/${tagname}"
          for LANG in ja en; do
            cp -r ${GITHUB_WORKSPACE}/built-docs/${LANG}/html "gh-pages/man/${tagname}/${LANG}"
          done
          cd gh-pages
          git config --local user.name "${GIT_USER}"
          git config --local user.email "${GIT_EMAIL}"
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
          git add man
          ret=0
          git commit -m "Deploy docs via GitHub Actions" || ret=$?
          if [ $ret -eq 0 ]; then
            git push origin gh-pages
          else
            echo "Nothing to deploy"
          fi
