name: CI

on: [push]

jobs:
  test_skip:
    runs-on: ubuntu-20.04
    if: github.repository == 'yomichi/dummy'
    steps:
      - name: test
        run: echo 'this is dummy'
  build:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'yomichi/GitHubActions-test'

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        mpisize: [1, 4, 16]
        ompsize: [1, 3]
        exclude:
          - os: macos-10.15
            mpisize: 4
          - os: macos-10.15
            mpisize: 16


    steps:
      - uses: actions/checkout@v3

      - name: make workspace
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: cmake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake $GITHUB_WORKSPACE

      - name: build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build .

      - name: ctest
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V

      - name: Check tag or not
        run: |
          is_tag=NO
          test $(echo ${GITHUB_REF:-"//"} | cut -d/ -f2) = "tags" && is_tag=YES
          if [ $is_tag = "YES" ]; then
          echo "This is tagged version"
          else
          echo "This is not tagged version"
          fi

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Print slug/short variables
        run: |
          echo "Original variables"
          echo " GITHUB_REPOSITORY - $GITHUB_REPOSITORY"
          echo " GITHUB_REF - $GITHUB_REF"
          echo "Slug variables"
          echo " GITHUB_REF_SLUG - ${{ env.GITHUB_REF_SLUG }}"    
          echo " GITHUB_HEAD_REF_SLUG - ${{ env.GITHUB_HEAD_REF_SLUG }}"
          echo " GITHUB_BASE_REF_SLUG - ${{ env.GITHUB_BASE_REF_SLUG }}"
          echo " GITHUB_REPOSITORY_SLUG - ${{ env.GITHUB_REPOSITORY_SLUG }}"
          echo "Slug URL variables"
          echo " GITHUB_REF_SLUG_URL - ${{ env.GITHUB_REF_SLUG_URL }}"
          echo " GITHUB_HEAD_REF_SLUG_URL - ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
          echo " GITHUB_BASE_REF_SLUG_URL - ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
          echo " GITHUB_REPOSITYRO_SLUG_URL - ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
          echo "Short SHA variables"
          echo " GITHUB_SHA_SHORT - ${{ env.GITHUB_SHA_SHORT }}"

      - name: matrix
        run: |
          echo "os"
          echo " ${{ matrix.os }}"
          echo "mpisize"
          echo " ${{ matrix.mpisize }}"
          echo "ompsize"
          echo " ${{ matrix.ompsize }}"

      - name: macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          echo "This is macOS"
          export FOO=FOO


      - name: Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          echo "This is Linux"
          export FOO=BAR

      - name: if
        run: |
          if [ ${{ runner.os }} = "macOS" ] ; then
            echo macOS
          else
            echo Linux
          fi
